# Generated by Django 5.1.1 on 2024-11-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interested_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
