# Generated by Django 5.1.1 on 2024-11-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_interested_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='interested_count',
        ),
    ]
