# Generated by Django 5.1.1 on 2024-11-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_interested_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_from_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_from_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_to_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_to_time',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
