# Generated by Django 5.1.1 on 2025-05-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
