# Generated by Django 5.1.1 on 2025-05-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_event_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
