# Generated by Django 5.1.1 on 2024-12-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('comment', 'Comment')], max_length=10, null=True),
        ),
    ]
