# Generated by Django 5.1.1 on 2024-12-21 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.userrelation'),
        ),
    ]
