# Generated by Django 5.1.1 on 2025-05-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_is_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('post_like', 'Post Like'), ('post_comment', 'Post Comment'), ('user_follow', 'User Follow'), ('event_interest', 'Event Interest'), ('event_comment', 'Event Comment'), ('general', 'General')], max_length=50, null=True),
        ),
    ]
