# Generated by Django 5.1.1 on 2024-12-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0002_alter_userprofile_facebook_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRelationships',
        ),
    ]
