# Generated by Django 5.1.1 on 2025-01-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0004_alter_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='primary_interest',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
