# Generated by Django 5.1.1 on 2025-01-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0005_alter_userprofile_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_full_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_primary_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
