# Generated by Django 5.1.1 on 2025-01-26 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0007_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='additional_links',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pinterest_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='threads_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tiktok_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='youtube_link',
        ),
        migrations.CreateModel(
            name='AdditionalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_links', to='appusers.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('twitter', 'Twitter'), ('threads', 'Threads'), ('linkedin', 'LinkedIn'), ('portfolio', 'Portfolio')], max_length=50)),
                ('url', models.URLField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='appusers.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'platform')},
            },
        ),
    ]
